apiVersion: v1
kind: Service
metadata:
  labels:
    app: ysm-nginx-svc
  annotations:
    example: ysm-svc
  name: ysm-nginx-svc-node-port
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ysm-nginx-pod
  sessionAffinity: None
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ysm-nginx-svc
  annotations:
    example: ysm-svc
  name: ysm-nginx-svc-external
  namespace: default
spec:
  externalName: www.baidu.com
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ysm-nginx-pod
  type: ExternalName

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    example: ysm-svc
  name: ysm-nginx-svc-headliness
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ysm-nginx-pod
  type: ClusterIP
  clusterIP: None
