apiVersion: v1
kind: Service
metadata:
  labels:
    app: ysm-nginx-src
  annotations:
    example: ysm-svc
  name: ysm-nginx-svc
  namespace: default
spec:
  ports:
  - nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ysm-nginx-pod
  sessionAffinity: None
  type: NodePort
