apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ysm-nginx-daemonset
  namespace: default
  labels:
    app: ysm-nginx-daemonset
spec:
  revisionHistoryLimit: 10
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels: # what pods will be controlled.
      pod: ysm-nginx-pod
    matchExpressions:
    - key: pod
      operator: In
      values:
      - ysm
      - ysm-nginx
      - ysm-nginx-pod
  template:
    metadata:
      name: ysm-nginx-pod
      labels:
        pod: ysm-nginx-pod
    spec:
      containers:
      - name: nginx
        image: nginx:1.17.1
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
