---
# the nginx pod.
apiVersion: v1
kind: Pod
metadata:
  annotations:
    example: "ysm-pod"
  labels:
    app: ysm-nginx-pod
  name: ysm-nginx-pod
  namespace: default
spec:
  containers:
  - image: nginx:1.17.1
    imagePullPolicy: IfNotPresent
    name: nginx-pod
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /var/ysm/logs/pod-termination-log
    terminationMessagePolicy: File
    volumeMounts:
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30

---
# the busybox pod
apiVersion: v1
kind: Pod
metadata:
  annotations:
    example: ysm-pod
  labels:
    app: ysm-busybox-pod
  name: ysm-busybox-pod
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - /bin/sh
      - -c
      - for i in 9 8 7 6 5 4 3 2 1;do echo $i;sleep 20;done
    name: busybox-pod
    imagePullPolicy: IfNotPresent
    name: nginx-pod
    terminationMessagePath: /var/ysm/logs/pod-termination-log
    terminationMessagePolicy: File
