apiVersion: v1
kind: Pod
metadata:
  annotations:
    example: "ysm-pod"
  labels:
    app: ysm-nginx-pod
  name: ysm-nginx-pod
  namespace: default
spec:
  containers:
  - image: nginx:1.17.1
    imagePullPolicy: IfNotPresent
    name: nginx-pod
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /var/ysm/logs/pod-termination-log
    terminationMessagePolicy: File
    volumeMounts:
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
